moderator:
  name: Moderator
  position: 10
  permissions:
    - view_dashboard
    - view_audit_log
    - view_feeds
    - manage_users
    - manage_reports
    - manage_taxonomies
    - create_statuses
    - reply_to_statuses
    - reblog_statuses
    - fav_statuses
admin:
  name: Admin
  position: 100
  permissions:
    - view_dashboard
    - view_audit_log
    - manage_users
    - manage_user_access
    - delete_user_data
    - manage_reports
    - manage_taxonomies
    - manage_federation
    - manage_settings
    - manage_blocks
    - manage_appeals
    - manage_rules
    - manage_invites
    - manage_announcements
    - manage_custom_emojis
    - manage_webhooks
    - manage_roles
    - create_statuses
    - reply_to_statuses
    - reblog_statuses
    - fav_statuses
owner:
  name: Owner
  position: 1000
  permissions:
    - administrator
poster:
  name: Poster
  position: 0
  permissions:
    - create_statuses
    - reply_to_statuses
    - reblog_statuses
    - fav_statuses
